#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-term-ansicolor
Version  : 1.3.2
Release  : 8
URL      : https://rubygems.org/downloads/term-ansicolor-1.3.2.gem
Source0  : https://rubygems.org/downloads/term-ansicolor-1.3.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: rubygem-term-ansicolor-bin
BuildRequires : ruby
BuildRequires : rubygem-gem_hadar
BuildRequires : rubygem-minitest_tu_shim
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-test-unit

%description
= Term::ANSIColor - ANSI escape sequences in Ruby
== Description
This library can be used to color/decolor strings using ANSI escape sequences.

%package bin
Summary: bin components for the rubygem-term-ansicolor package.
Group: Binaries

%description bin
bin components for the rubygem-term-ansicolor package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n term-ansicolor-1.3.2
gem spec %{SOURCE0} -l --ruby > rubygem-term-ansicolor.gemspec

%build
gem build rubygem-term-ansicolor.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
term-ansicolor-1.3.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/term-ansicolor-1.3.2
ruby -v -I.:lib:tests test*/test_*.rb
ruby -v -I.:lib:tests test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/term-ansicolor-1.3.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/bin/cdiff
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/bin/colortab
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/bin/decolor
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/bin/term_display
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/bin/term_mandel
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/ColorTest.gif
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/Mona_Lisa.jpg
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/Stilleben.jpg
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/example.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/lambda-red-plain.ppm
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/lambda-red.png
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/lambda-red.ppm
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/pacman.jpg
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/smiley.png
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/examples/wool.jpg
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/lib/term/ansicolor.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/lib/term/ansicolor/.keep
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/lib/term/ansicolor/attribute.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/lib/term/ansicolor/ppm_reader.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/lib/term/ansicolor/rgb_color_metrics.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/lib/term/ansicolor/rgb_triple.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/lib/term/ansicolor/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/term-ansicolor.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/tests/ansicolor_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/tests/attribute_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/tests/ppm_reader_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/tests/rgb_color_metrics_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/tests/rgb_triple_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/term-ansicolor-1.3.2/tests/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/term-ansicolor-1.3.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/cdiff
/usr/bin/colortab
/usr/bin/decolor
/usr/bin/term_display
/usr/bin/term_mandel
